Repository GET-to-the-POINT/unicat-api, pull requests merged in 2025-03, with the labels that each got.

#13 release 1.1.13
  build.gradle
  gradle.properties
  src/main/java/taeniverse/unicatApi/UnicatApiApplication.java
  src/main/java/taeniverse/unicatApi/component/auth/MemberDetails.java
  src/main/java/taeniverse/unicatApi/component/filter/ReissueAccessTokenFilter.java
  src/main/java/taeniverse/unicatApi/component/oauth2/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/taeniverse/unicatApi/component/oauth2/CustomOAuth2AuthorizationRequestResolver.java
  src/main/java/taeniverse/unicatApi/component/oauth2/CustomOAuth2User.java
  src/main/java/taeniverse/unicatApi/component/oauth2/GoogleOAuth2UserInfo.java
  src/main/java/taeniverse/unicatApi/component/oauth2/KakaoOAuth2UserInfo.java
  src/main/java/taeniverse/unicatApi/component/oauth2/MultiBearerTokenResolver.java
  src/main/java/taeniverse/unicatApi/component/oauth2/OAuth2UserInfo.java
  src/main/java/taeniverse/unicatApi/component/oauth2/OAuth2UserInfoFactory.java
  src/main/java/taeniverse/unicatApi/component/propertie/AppProperties.java
  src/main/java/taeniverse/unicatApi/component/schema/ErrorResponse.java
  src/main/java/taeniverse/unicatApi/component/schema/FieldError.java
  src/main/java/taeniverse/unicatApi/component/schema/UnauthorizedErrorResponse.java
  src/main/java/taeniverse/unicatApi/component/util/JwtUtil.java
  src/main/java/taeniverse/unicatApi/config/CookieProperties.java
  src/main/java/taeniverse/unicatApi/config/JwtConfig.java
  src/main/java/taeniverse/unicatApi/config/SecurityConfig.java
  src/main/java/taeniverse/unicatApi/config/SwaggerConfig.java
  src/main/java/taeniverse/unicatApi/config/ValidationConfig.java
  src/main/java/taeniverse/unicatApi/constant/Role.java
  src/main/java/taeniverse/unicatApi/mvc/controller/AuthController.java
  src/main/java/taeniverse/unicatApi/mvc/controller/JwkSetController.java
  src/main/java/taeniverse/unicatApi/mvc/controller/OAuthLinkController.java
  src/main/java/taeniverse/unicatApi/mvc/controller/SignController.java
  src/main/java/taeniverse/unicatApi/mvc/controller/TokenController.java
  src/main/java/taeniverse/unicatApi/mvc/model/dto/GoogleResponse.java
  src/main/java/taeniverse/unicatApi/mvc/model/dto/KakaoResponse.java
  src/main/java/taeniverse/unicatApi/mvc/model/dto/NaverResponse.java
  src/main/java/taeniverse/unicatApi/mvc/model/dto/OAuth2Response.java
  src/main/java/taeniverse/unicatApi/mvc/model/dto/OAuthDTO.java
  src/main/java/taeniverse/unicatApi/mvc/model/dto/PrincipalDetails.java
  src/main/java/taeniverse/unicatApi/mvc/model/dto/SignDto.java
  src/main/java/taeniverse/unicatApi/mvc/model/dto/oauth/OAuthLinkDto.java
  src/main/java/taeniverse/unicatApi/mvc/model/dto/sign/SignInDto.java
  src/main/java/taeniverse/unicatApi/mvc/model/dto/sign/SignUpDto.java
  src/main/java/taeniverse/unicatApi/mvc/model/entity/Role.java
  src/main/java/taeniverse/unicatApi/mvc/repository/MemberRepository.java
  src/main/java/taeniverse/unicatApi/mvc/service/AuthService.java
  src/main/java/taeniverse/unicatApi/mvc/service/CustomOAuth2UserService.java
  src/main/java/taeniverse/unicatApi/mvc/service/MemberDetailsService.java
  src/main/java/taeniverse/unicatApi/temp/OAuth2UserInfo.java
  src/main/java/taeniverse/unicatApi/util/JwtUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/main/resources/messages_en.properties
  src/main/resources/messages_jp.properties
  src/main/resources/messages_ko.properties
  src/test/java/taeniverse/unicatApi/mvc/controller/SignControllerTest.java
Labels: enhancement

#14 :bug: 토큰 검증 실패 케이스 추가
  gradle.properties
  src/main/java/taeniverse/unicatApi/component/oauth2/CustomAuthenticationEntryPoint.java
  src/main/java/taeniverse/unicatApi/config/SecurityConfig.java
  src/main/resources/messages_en.properties
  src/main/resources/messages_jp.properties
  src/main/resources/messages_ko.properties
Labels: bug

#16 15 oauth2 계정 링크
  src/main/java/taeniverse/unicatApi/component/filter/ReissueAccessTokenFilter.java
  src/main/java/taeniverse/unicatApi/component/oauth2/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/taeniverse/unicatApi/component/oauth2/CustomOAuth2User.java
  src/main/java/taeniverse/unicatApi/component/oauth2/MultiBearerTokenResolver.java
  src/main/java/taeniverse/unicatApi/component/util/JwtUtil.java
  src/main/java/taeniverse/unicatApi/mvc/model/entity/Member.java
  src/main/java/taeniverse/unicatApi/mvc/model/entity/OAuthLink.java
  src/main/java/taeniverse/unicatApi/mvc/service/AuthService.java
  src/main/java/taeniverse/unicatApi/mvc/service/CustomOAuth2UserService.java
Labels: enhancement

#21 :memo: 토큰 프로세스 스웨거 문서 작성
  src/main/java/gettothepoint/unicatapi/presentation/controller/auth/AuthController.java
Labels: enhancement

#24 20 결제 정보 저장
  src/main/java/gettothepoint/unicatapi/application/service/payment/PaymentCancelService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/PaymentService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/SubscriptionService.java
  src/main/java/gettothepoint/unicatapi/common/propertie/AppProperties.java
  src/main/java/gettothepoint/unicatapi/domain/constant/payment/SubscriptionStatus.java
  src/main/java/gettothepoint/unicatapi/domain/dto/payment/CancelPaymentRequest.java
  src/main/java/gettothepoint/unicatapi/domain/dto/payment/TossPaymentResponse.java
  src/main/java/gettothepoint/unicatapi/domain/entity/Payment.java
  src/main/java/gettothepoint/unicatapi/domain/entity/Subscription.java
  src/main/java/gettothepoint/unicatapi/domain/repository/PaymentRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/SubscriptionRepository.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/payment/PaymentController.java
  src/main/resources/application-dev.yml
  src/main/resources/application.yml
Labels: enhancement

#26 25 payment log
  src/main/java/gettothepoint/unicatapi/application/service/payment/PaymentCancelService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/PaymentService.java
  src/main/java/gettothepoint/unicatapi/domain/entity/CancelPayment.java
  src/main/java/gettothepoint/unicatapi/domain/entity/Order.java
  src/main/java/gettothepoint/unicatapi/domain/entity/Payment.java
  src/main/java/gettothepoint/unicatapi/domain/repository/CancelPaymentRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/PaymentRepository.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/payment/PaymentController.java
Labels: enhancement

#58 PR-storage-get-voices
  src/main/java/gettothepoint/unicatapi/application/service/storage/FileStorageService.java
  src/main/java/gettothepoint/unicatapi/application/service/storage/SampleVoiceService.java
  src/main/java/gettothepoint/unicatapi/application/service/storage/SupabaseStorageService.java
  src/main/java/gettothepoint/unicatapi/domain/dto/SampleVoice.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/StorageController.java
  src/test/java/gettothepoint/unicatapi/mvc/controller/StorageControllerTest.java
Labels: 기능

#60 PR-validation-password
  src/main/java/gettothepoint/unicatapi/application/service/MemberService.java
  src/main/java/gettothepoint/unicatapi/common/validation/email/UniqueEmail.java
  src/main/java/gettothepoint/unicatapi/common/validation/email/UniqueEmailValidator.java
  src/main/java/gettothepoint/unicatapi/common/validation/fieldcompare/CompareResult.java
  src/main/java/gettothepoint/unicatapi/common/validation/fieldcompare/CompareTarget.java
  src/main/java/gettothepoint/unicatapi/common/validation/fieldcompare/FieldComparison.java
  src/main/java/gettothepoint/unicatapi/common/validation/fieldcompare/FieldComparisonValidator.java
  src/main/java/gettothepoint/unicatapi/domain/dto/sign/SignUpDto.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/auth/SignController.java
Labels: 버그

#64 PR-refactoring-naming
  build.gradle
  src/main/java/gettothepoint/unicatapi/application/service/AuthService.java
  src/main/java/gettothepoint/unicatapi/application/service/MemberService.java
  src/main/java/gettothepoint/unicatapi/application/service/ProjectService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/OrderService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/PaymentCancelService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/PaymentService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/SubscriptionService.java
  src/main/java/gettothepoint/unicatapi/application/service/schedule/YoutubeDataScheduler.java
  src/main/java/gettothepoint/unicatapi/application/service/storage/FileStorageService.java
  src/main/java/gettothepoint/unicatapi/application/service/storage/SampleVoiceService.java
  src/main/java/gettothepoint/unicatapi/application/service/storage/SupabaseStorageService.java
  src/main/java/gettothepoint/unicatapi/application/service/video/UploadProgressService.java
  src/main/java/gettothepoint/unicatapi/application/service/video/VideoDataUpdateService.java
  src/main/java/gettothepoint/unicatapi/application/service/video/VideoStatisticsEntityService.java
  src/main/java/gettothepoint/unicatapi/application/service/video/YoutubeDataService.java
  src/main/java/gettothepoint/unicatapi/application/service/video/YoutubeUploadService.java
  src/main/java/gettothepoint/unicatapi/common/propertie/AppProperties.java
  src/main/java/gettothepoint/unicatapi/domain/dto/payment/OrderRequest.java
  src/main/java/gettothepoint/unicatapi/domain/dto/payment/PaymentHistoryDto.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/ProjectResponse.java
  src/main/java/gettothepoint/unicatapi/domain/dto/storage/SampleVoice.java
  src/main/java/gettothepoint/unicatapi/domain/dto/storage/StorageUpload.java
  src/main/java/gettothepoint/unicatapi/domain/entity/BaseEntity.java
  src/main/java/gettothepoint/unicatapi/domain/entity/Member.java
  src/main/java/gettothepoint/unicatapi/domain/entity/Project.java
  src/main/java/gettothepoint/unicatapi/domain/entity/dashboard/Project.java
  src/main/java/gettothepoint/unicatapi/domain/entity/dashboard/Section.java
  src/main/java/gettothepoint/unicatapi/domain/entity/member/Member.java
  src/main/java/gettothepoint/unicatapi/domain/entity/member/OAuthLink.java
  src/main/java/gettothepoint/unicatapi/domain/entity/payment/Order.java
  src/main/java/gettothepoint/unicatapi/domain/entity/payment/Payment.java
  src/main/java/gettothepoint/unicatapi/domain/entity/payment/Subscription.java
  src/main/java/gettothepoint/unicatapi/domain/entity/video/UploadVideo.java
  src/main/java/gettothepoint/unicatapi/domain/entity/video/Video.java
  src/main/java/gettothepoint/unicatapi/domain/entity/video/VideoHistory.java
  src/main/java/gettothepoint/unicatapi/domain/repository/MemberRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/OAuthLinkRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/OrderRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/PaymentRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/ProjectRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/SubscriptionRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/video/UploadVideoRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/video/VideoHistoryRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/video/VideoUpdateRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/video/VideosRepository.java
  src/main/java/gettothepoint/unicatapi/domain/repository/video/YouTubeUploadRepository.java
  src/main/java/gettothepoint/unicatapi/infrastructure/config/DataLoader.java
  src/main/java/gettothepoint/unicatapi/infrastructure/security/oAuth2Client/CustomOAuth2UserService.java
  src/main/java/gettothepoint/unicatapi/infrastructure/security/youtube/YoutubeOAuth2Service.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/StorageController.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/payment/OrderController.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/payment/PaymentController.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/video/VideoStatisticsEntityController.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/video/YouTubeUploadController.java
  src/main/resources/application.yml
Labels: 개선

#61 PR-project-entity
  src/main/java/gettothepoint/unicatapi/domain/entity/Member.java
  src/main/java/gettothepoint/unicatapi/domain/entity/Project.java
  src/main/java/gettothepoint/unicatapi/domain/entity/Section.java
Labels: 기능

#72 57 auth validation email
  build.gradle
  src/main/java/gettothepoint/unicatapi/application/service/MemberService.java
  src/main/java/gettothepoint/unicatapi/application/service/email/EmailService.java
  src/main/java/gettothepoint/unicatapi/common/propertie/AppProperties.java
  src/main/java/gettothepoint/unicatapi/common/propertie/MailProperties.java
  src/main/java/gettothepoint/unicatapi/common/util/UrlUtil.java
  src/main/java/gettothepoint/unicatapi/domain/dto/email/EmailRequestDto.java
  src/main/java/gettothepoint/unicatapi/domain/dto/email/VerificationCodeDto.java
  src/main/java/gettothepoint/unicatapi/domain/entity/VerificationCode.java
  src/main/java/gettothepoint/unicatapi/domain/entity/member/Member.java
  src/main/java/gettothepoint/unicatapi/domain/repository/VerificationCodeRepository.java
  src/main/java/gettothepoint/unicatapi/infrastructure/config/MailConfig.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/email/EmailController.java
  src/main/resources/application.yml
Labels: 기능

#75 PR-vidoes-tts-create
  build.gradle
  src/main/java/gettothepoint/unicatapi/application/service/TextToSpeechService.java
  src/main/java/gettothepoint/unicatapi/application/service/storage/SupabaseStorageService.java
  src/main/java/gettothepoint/unicatapi/domain/entity/dashboard/Section.java
  src/test/java/gettothepoint/unicatapi/mvc/service/TextToSpeechServiceTest.java
Labels: 기능

#76 PR-Auth-passwrod-reset
  src/main/java/gettothepoint/unicatapi/application/service/MemberService.java
  src/main/java/gettothepoint/unicatapi/application/service/email/EmailService.java
  src/main/java/gettothepoint/unicatapi/application/service/password/PasswordService.java
  src/main/java/gettothepoint/unicatapi/domain/dto/password/ChangePasswordDto.java
  src/main/java/gettothepoint/unicatapi/domain/entity/member/Member.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/passwordreset/PasswordResetController.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/passwordreset/PasswordResetPageController.java
  src/main/resources/templates/reset-password.html
Labels: 기능

#80 PR-project-post-project
  src/main/java/gettothepoint/unicatapi/application/service/ProjectService.java
  src/main/java/gettothepoint/unicatapi/application/service/SectionService.java
  src/main/java/gettothepoint/unicatapi/application/service/TextToSpeechService.java
  src/main/java/gettothepoint/unicatapi/common/propertie/AppProperties.java
  src/main/java/gettothepoint/unicatapi/common/util/MultipartFileUtil.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/SectionRequest.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/SectionResponse.java
  src/main/java/gettothepoint/unicatapi/domain/entity/dashboard/Section.java
  src/main/java/gettothepoint/unicatapi/domain/repository/SectionRepository.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/projetct/ProjectController.java
  src/main/resources/application.yml
Labels: 기능

#88 PR-Password-post-verify
  src/main/java/gettothepoint/unicatapi/application/service/password/PasswordService.java
  src/main/java/gettothepoint/unicatapi/presentation/password/PasswordController.java
  src/test/java/gettothepoint/unicatapi/presentation/password/PasswordControllerIntegrationTest.java
  src/test/java/gettothepoint/unicatapi/test/config/TestDummyEmailServiceConfiguration.java
Labels: 기능

#94 PR-POST-projects-?-sections-?-script
  build.gradle
  src/main/java/gettothepoint/unicatapi/application/service/OpenAiService.java
  src/main/java/gettothepoint/unicatapi/common/propertie/AppProperties.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/ScriptRequest.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/ScriptResponse.java
  src/main/java/gettothepoint/unicatapi/domain/entity/dashboard/Project.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/projetct/ProjectController.java
  src/main/resources/application.yml
  src/test/java/gettothepoint/unicatapi/application/service/OpenAiServiceTest.java
  src/test/java/gettothepoint/unicatapi/presentation/controller/ProjectControllerTest.java
Labels: 기능

#108 PR-post-rojectssections
  src/main/java/gettothepoint/unicatapi/application/service/OpenAiService.java
  src/main/java/gettothepoint/unicatapi/application/service/ProjectService.java
  src/main/java/gettothepoint/unicatapi/application/service/SectionService.java
  src/main/java/gettothepoint/unicatapi/application/service/storage/FileStorageService.java
  src/main/java/gettothepoint/unicatapi/application/service/storage/SupabaseStorageService.java
  src/main/java/gettothepoint/unicatapi/common/propertie/AppProperties.java
  src/main/java/gettothepoint/unicatapi/common/util/MultipartFileUtil.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/CreateResourceResponse.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/ImageResponse.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/PromptRequest.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/ScriptResponse.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/UploadResourceRequest.java
  src/main/java/gettothepoint/unicatapi/domain/entity/dashboard/Section.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/projetct/ProjectController.java
  src/main/resources/application.yml
  src/test/java/gettothepoint/unicatapi/application/service/OpenAiServiceTest.java
  src/test/java/gettothepoint/unicatapi/presentation/controller/ProjectControllerTest.java
Labels: 개선

#111 PR-refactoring-domain
  src/main/java/gettothepoint/unicatapi/application/service/payment/OrderService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/PaymentService.java
  src/main/java/gettothepoint/unicatapi/domain/dto/payment/PaymentHistoryResponse.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/payment/OrderController.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/payment/PaymentController.java
Labels: 개선

#112 PR 104-get-projects
  src/main/java/gettothepoint/unicatapi/application/service/ProjectService.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/ProjectDto.java
  src/main/java/gettothepoint/unicatapi/infrastructure/config/SecurityConfig.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/projetct/ProjectController.java
  src/test/java/gettothepoint/unicatapi/presentation/controller/ProjectControllerTest.java
Labels: 기능

#113 PR-project-youtube-get-statistics
  build.gradle
  src/main/java/gettothepoint/unicatapi/application/service/youtube/YouTubeAnalyticsProxyService.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/project/ProjectController.java
  src/main/resources/core/application-oauth.yml
  src/test/java/gettothepoint/unicatapi/presentation/controller/ProjectControllerTest.java
Labels: 개선

#122 PR-feat-로깅
  build.gradle
  docker-compose.yml
  loki-config.yaml
  src/main/resources/logback.xml
Labels: 기능

#127 PR-feat-스토리지-서비스-구현
  src/main/java/gettothepoint/unicatapi/application/service/OpenAiService.java
  src/main/java/gettothepoint/unicatapi/application/service/storage/SupabaseStorageServiceImpl.java
Labels: 개선, 기능

#131 PR-bug-supabase-upload
  src/main/java/gettothepoint/unicatapi/application/service/storage/LocalStorageService.java
  src/main/java/gettothepoint/unicatapi/application/service/storage/SupabaseStorageServiceImpl.java
Labels: 버그

#139 PR 129-feat-멤버에-이름과-전화번호-추가
  src/main/java/gettothepoint/unicatapi/application/service/AuthService.java
  src/main/java/gettothepoint/unicatapi/application/service/email/EmailService.java
  src/main/java/gettothepoint/unicatapi/application/service/member/MemberService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/BillingService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/PaymentService.java
  src/main/java/gettothepoint/unicatapi/domain/dto/member/MemberResponse.java
  src/main/java/gettothepoint/unicatapi/domain/dto/member/MemberUpdateDto.java
  src/main/java/gettothepoint/unicatapi/domain/dto/sign/SignUpDto.java
  src/main/java/gettothepoint/unicatapi/domain/entity/member/Member.java
  src/main/java/gettothepoint/unicatapi/domain/entity/payment/Billing.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/member/EmailController.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/member/MemberController.java
  src/main/resources/messages_ko.properties
Labels: 개선

#142 PR-bug-인공지능-이미지-생성-잘못됨
  src/main/java/gettothepoint/unicatapi/application/service/OpenAiService.java
  src/main/java/gettothepoint/unicatapi/application/service/storage/SupabaseStorageServiceImpl.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/SectionResourceRequest.java
  src/main/java/gettothepoint/unicatapi/domain/entity/dashboard/Section.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/AssetsController.java
  src/main/resources/application.yml
Labels: 버그

#145 PR 141-feat-결제-리디렉션
  src/main/java/gettothepoint/unicatapi/common/propertie/AppProperties.java
  src/main/java/gettothepoint/unicatapi/domain/dto/payment/SubscriptionRequest.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/payment/SubscriptionController.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/payment/TossPaymentController.java
  src/main/resources/application.yml
Labels: 개선

#150 PR 149-feat-이메일-검증-시스템
  src/main/java/gettothepoint/unicatapi/application/service/member/MemberService.java
Labels: 개선

#159 PR 157- feat- 리팩토링
  src/main/java/gettothepoint/unicatapi/application/service/AuthService.java
  src/main/java/gettothepoint/unicatapi/application/service/email/EmailService.java
  src/main/java/gettothepoint/unicatapi/application/service/member/MemberService.java
  src/main/java/gettothepoint/unicatapi/application/service/member/password/PasswordService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/BillingProcessingService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/OrderService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/PaymentService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/PlanService.java
  src/main/java/gettothepoint/unicatapi/application/service/payment/SubscriptionService.java
  src/main/java/gettothepoint/unicatapi/domain/dto/member/MemberResponse.java
  src/main/java/gettothepoint/unicatapi/domain/entity/member/Member.java
  src/main/java/gettothepoint/unicatapi/domain/entity/payment/Order.java
  src/main/java/gettothepoint/unicatapi/domain/entity/payment/Plan.java
  src/main/java/gettothepoint/unicatapi/domain/entity/payment/Subscription.java
  src/main/java/gettothepoint/unicatapi/domain/repository/PlanRepository.java
  src/main/java/gettothepoint/unicatapi/infrastructure/config/DataInitializer.java
  src/main/java/gettothepoint/unicatapi/infrastructure/security/oauth2/client/CustomOAuth2AuthenticationSuccessHandler.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/payment/SubscriptionController.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/payment/TossPaymentController.java
Labels: 개선

#162 PR-Ai 자동화 기능
  src/main/java/gettothepoint/unicatapi/application/service/OpenAiService.java
  src/main/java/gettothepoint/unicatapi/application/service/media/ArtifactService.java
  src/main/java/gettothepoint/unicatapi/common/propertie/AppProperties.java
  src/main/java/gettothepoint/unicatapi/domain/dto/project/AutoArtifact.java
  src/main/java/gettothepoint/unicatapi/presentation/controller/project/ProjectController.java
  src/main/resources/application.yml
Labels: 기능

#163 httpclient
  src/main/java/gettothepoint/unicatapi/application/service/storage/SupabaseStorageServiceImpl.java
  src/main/java/gettothepoint/unicatapi/application/service/voice/SuperToneService.java
  src/main/java/gettothepoint/unicatapi/infrastructure/config/HttpClientConfig.java
  src/test/java/gettothepoint/unicatapi/application/service/OpenAiServiceTest.java
  src/test/java/gettothepoint/unicatapi/application/service/voice/SuperToneServiceTest.java
  src/test/java/gettothepoint/unicatapi/test/config/TestDummyEmailServiceConfiguration.java
Labels: 개선, 기능
